Repository QuEraComputing/kirin, pull requests merged in 2025-05, with the labels that each got.

#395 fix type hint error for method
  src/kirin/ir/attrs/types.py
  src/kirin/lowering/python/glob.py
  test/lowering/test_method_hint.py
Labels: backport 0.17

#391 Adding special slice attribute
  src/kirin/dialects/py/indexing.py
  src/kirin/dialects/py/slice.py
  src/kirin/types.py
  test/dialects/pystmts/test_slice.py
Labels: breaking

#403 feat: add result value to function
  src/kirin/dialects/func/stmts.py
Labels: enhancement, backport 0.18

#411 improve type hints of get_casted
  src/kirin/interp/frame.py
Labels: backport 0.18

#412 fix hash(-1) == hash(-2) collision
  src/kirin/ir/attrs/py.py
Labels: need test, backport 0.17, backport 0.18
