Repository QuEraComputing/kirin, pull requests merged in 2025-06, with the labels that each got.

#422 Fix typo in inline pass
  src/kirin/passes/inline.py
  test/passes/test_inline_pass.py
Labels: breaking

#421 RFC: support overwriting existing method
  src/kirin/analysis/callgraph.py
  src/kirin/dialects/func/stmts.py
  src/kirin/ir/__init__.py
  src/kirin/ir/group.py
  src/kirin/ir/method.py
  src/kirin/ir/traits/__init__.py
  src/kirin/ir/traits/callable.py
  test/ir/test_duplicated.py
  test/ir/test_group.py
Labels: IR node, need test

#429 Implement ilist any and all methods
  src/kirin/dialects/ilist/__init__.py
  src/kirin/dialects/ilist/_wrapper.py
  src/kirin/dialects/ilist/interp.py
  src/kirin/dialects/ilist/stmts.py
  test/dialects/test_ilist_wrapper.py
Labels: backport 0.17, backport 0.18
