Repository QuEraComputing/kirin, pull requests merged in 2025-04, with the labels that each got.

#344 support annotated assign
  src/kirin/dialects/ilist/interp.py
  src/kirin/dialects/ilist/lowering.py
  src/kirin/dialects/ilist/stmts.py
  src/kirin/dialects/lowering/func.py
  src/kirin/dialects/lowering/range.py
  src/kirin/dialects/py/assign.py
  src/kirin/dialects/py/attr.py
  src/kirin/dialects/py/builtin.py
  src/kirin/dialects/py/iterable.py
  src/kirin/dialects/py/len.py
  src/kirin/dialects/py/slice.py
  src/kirin/lowering/__init__.py
  src/kirin/lowering/python/dialect.py
  src/kirin/lowering/python/dialect.pyi
  src/kirin/lowering/python/lowering.py
  src/kirin/passes/typeinfer.py
  src/kirin/registry.py
  src/kirin/registry.pyi
  src/kirin/rewrite/__init__.py
  src/kirin/rewrite/aggressive/fold.py
  src/kirin/rewrite/type_assert.py
  test/dialects/py/__init__.py
  test/dialects/py/test_assign.py
Labels: enhancement, python lowering, dialect: py, dialect: python types

#346 support binding for contextmanager
  src/kirin/lowering/python/lowering.py
  src/kirin/lowering/python/traits.py
  test/lowering/test_with_binding.py
Labels: python lowering

#348 fix multi assign
  src/kirin/dialects/py/assign.py
  test/lowering/test_assign.py
Labels: bug, python lowering

#339 fix common subexpression elimination
  src/kirin/rewrite/cse.py
  test/rewrite/test_cse_rewrite.py
Labels: bug, rewrite

#350 refactor check type
  src/kirin/decl/__init__.py
  src/kirin/decl/emit/check_type.py
  src/kirin/dialects/func/stmts.py
  src/kirin/dialects/py/constant.py
  src/kirin/exceptions.py
  src/kirin/ir/nodes/base.py
  src/kirin/ir/nodes/block.py
  src/kirin/ir/nodes/region.py
  src/kirin/ir/nodes/stmt.py
  test/dialects/test_func.py
  test/verify/test_typecheck.py
Labels: breaking, backport

#351 improve lowering lineno precision
  src/kirin/ir/group.py
  src/kirin/lowering/python/lowering.py
Labels: bug, python lowering

#352 rework exceptions and improve error handling
  src/kirin/__init__.py
  src/kirin/decl/emit/check_type.py
  src/kirin/decl/emit/verify.py
  src/kirin/dialects/func/stmts.py
  src/kirin/dialects/lowering/call.py
  src/kirin/dialects/module.py
  src/kirin/dialects/scf/stmts.py
  src/kirin/exception.py
  src/kirin/exceptions.py
  src/kirin/ir/__init__.py
  src/kirin/ir/exception.py
  src/kirin/ir/group.py
  src/kirin/ir/method.py
  src/kirin/ir/nodes/base.py
  src/kirin/ir/nodes/block.py
  src/kirin/ir/nodes/region.py
  src/kirin/ir/nodes/stmt.py
  src/kirin/ir/traits/symbol.py
  src/kirin/lowering/exception.py
  src/kirin/lowering/frame.py
  src/kirin/lowering/python/lowering.py
  src/kirin/lowering/state.py
  src/kirin/source.py
  test/dialects/scf/test_for.py
  test/dialects/test_func.py
  test/ir/test_duplicated.py
  test/verify/test_typecheck.py
Labels: enhancement, breaking

#370 Add get_present_trait method to statement class
  src/kirin/ir/method.py
  src/kirin/ir/nodes/stmt.py
Labels: enhancement, backport 0.16

#369 refactor interp to clean up APIs + improve stacktrace
  src/kirin/analysis/const/prop.py
  src/kirin/analysis/forward.py
  src/kirin/dialects/cf/constprop.py
  src/kirin/dialects/func/emit.py
  src/kirin/dialects/scf/absint.py
  src/kirin/dialects/scf/constprop.py
  src/kirin/dialects/scf/interp.py
  src/kirin/dialects/scf/typeinfer.py
  src/kirin/emit/abc.py
  src/kirin/emit/abc.pyi
  src/kirin/emit/str.py
  src/kirin/interp/abstract.py
  src/kirin/interp/base.py
  src/kirin/interp/concrete.py
  src/kirin/interp/frame.py
  src/kirin/interp/result.py
  src/kirin/interp/state.py
  src/kirin/interp/value.py
  src/kirin/ir/nodes/stmt.py
Labels: breaking, interpreter

#316 Inline `len` for `IList`
  src/kirin/dialects/ilist/rewrite/__init__.py
  src/kirin/dialects/ilist/rewrite/hint_len.py
  src/kirin/passes/__init__.py
  src/kirin/passes/abc.py
  src/kirin/passes/aggressive/fold.py
  src/kirin/passes/default.py
  src/kirin/passes/fold.py
  src/kirin/passes/hint_const.py
  src/kirin/passes/typeinfer.py
  src/kirin/prelude.py
  test/dialects/test_infer_len.py
Labels: breaking

#371 feat: add a canonicalize + post inference hook to ir.Dialect
  src/kirin/dialects/ilist/rewrite/const.py
  src/kirin/dialects/ilist/rewrite/hint_len.py
  src/kirin/dialects/ilist/rewrite/list.py
  src/kirin/dialects/ilist/rewrite/unroll.py
  src/kirin/dialects/scf/trim.py
  src/kirin/ir/dialect.py
  src/kirin/passes/canonicalize.py
  src/kirin/passes/default.py
  src/kirin/passes/post_inference.py
  src/kirin/passes/typeinfer.py
Labels: breaking, rewrite

#372 cleanup rewrite exports
  src/kirin/dialects/ilist/passes.py
  src/kirin/dialects/ilist/rewrite/const.py
  src/kirin/dialects/ilist/rewrite/list.py
  src/kirin/dialects/ilist/rewrite/unroll.py
  src/kirin/dialects/scf/trim.py
  src/kirin/dialects/scf/unroll.py
  src/kirin/rewrite/abc.py
  src/kirin/rewrite/chain.py
  src/kirin/rewrite/fixpoint.py
  src/kirin/rewrite/result.py
  src/kirin/rewrite/walk.py
Labels: breaking, rewrite

#373 feat: improve error message of calling class method
  src/kirin/dialects/func/stmts.py
  src/kirin/ir/method.py
  src/kirin/lowering/python/lowering.py
  src/kirin/passes/default.py
  src/kirin/source.py
  test/program/py/test_class.py
Labels: backport 0.16

#374 support stacktrace in interpreter
  src/kirin/analysis/forward.py
  src/kirin/exception.py
  src/kirin/interp/__init__.py
  src/kirin/interp/base.py
  src/kirin/interp/exceptions.py
  src/kirin/interp/frame.py
  src/kirin/ir/group.py
  src/kirin/ir/method.py
  src/kirin/lowering/python/lowering.py
  src/kirin/lowering/state.py
  src/kirin/source.py
  test/emit/test_julia.py
  test/interp/test_func.py
  test/interp/test_select.py
  test/program/py/aha/gaga.py
  test/program/py/test_basic.py
Labels: interpreter

#375 setup pyright
  .github/workflows/ci.yml
  .github/workflows/devdoc.yml
  .github/workflows/doc.yml
  .github/workflows/lint.yml
  .github/workflows/pub_doc.yml
  .github/workflows/release.yml
  pyproject.toml
Labels: devops

#376 fix: more precise exception
  src/kirin/exception.py
  src/kirin/ir/method.py
Labels: backport 0.16

#377 rework error handling in compiler
  src/kirin/dialects/py/assertion.py
  src/kirin/dialects/py/assign.py
  src/kirin/exception.py
  src/kirin/interp/__init__.py
  src/kirin/interp/base.py
  src/kirin/interp/exceptions.py
  src/kirin/ir/__init__.py
  src/kirin/ir/exception.py
  src/kirin/ir/group.py
  src/kirin/ir/method.py
  src/kirin/ir/nodes/block.py
  src/kirin/ir/nodes/region.py
  src/kirin/lowering/exception.py
  src/kirin/lowering/python/dialect.py
  src/kirin/lowering/python/glob.py
  src/kirin/lowering/python/lowering.py
  src/kirin/lowering/state.py
  src/kirin/source.py
  test/interp/test_func.py
  test/interp/test_select.py
  test/lowering/test_with.py
  test/program/py/test_basic.py
Labels: backport 0.16, backport 0.17

#386 rename get_attr_or_prop -> get_attribute
  src/kirin/ir/nodes/stmt.py
  src/kirin/ir/traits/symbol.py
Labels: breaking, IR node

#387 fix walk order
  src/kirin/rewrite/walk.py
Labels: bug
